package com.flowpilot.flowpilot.admin.service;

import com.flowpilot.flowpilot.admin.model.AdminDepartment;
import com.flowpilot.flowpilot.admin.model.AdminDepartmentMember;
import com.flowpilot.flowpilot.admin.repository.AdminDepartmentMemberRepository;
import com.flowpilot.flowpilot.admin.repository.AdminDepartmentsRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class AdminDepartmentMemberService {

    private final AdminDepartmentMemberRepository memberRepository;
    private final AdminDepartmentsRepository departmentRepository;

    public AdminDepartmentMemberService(
            AdminDepartmentMemberRepository memberRepository,
            AdminDepartmentsRepository departmentRepository) {

        this.memberRepository = memberRepository;
        this.departmentRepository = departmentRepository;
    }

    public List<AdminDepartmentMember> getMembers(Long departmentId) {

        AdminDepartment department =
                departmentRepository.findById(departmentId)
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Department not found"
                                ));

        return memberRepository.findByDepartment(department);
    }

    public AdminDepartmentMember addMember(
            Long departmentId,
            AdminDepartmentMember member) {

        AdminDepartment department =
                departmentRepository.findById(departmentId)
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Department not found"
                                ));

        /*
         * Generate employee ID automatically.
         *
         * Example:
         * EMP009 -> EMP010
         * EMP010 -> EMP011
         */
        AdminDepartmentMember lastMember =
                memberRepository.findTopByOrderByEmployeeIdDesc();

        int nextNumber = 1;

        if (lastMember != null &&
                lastMember.getEmployeeId() != null) {

            String lastEmployeeId =
                    lastMember.getEmployeeId();

            if (lastEmployeeId.startsWith("EMP")) {

                try {
                    int lastNumber =
                            Integer.parseInt(
                                    lastEmployeeId.substring(3)
                            );

                    nextNumber = lastNumber + 1;

                } catch (NumberFormatException ignored) {
                    // Keep nextNumber as 1
                }
            }
        }

        String employeeId =
                String.format("EMP%03d", nextNumber);

        member.setId(null);
        member.setDepartment(department);

        // Employee ID is generated by backend
        member.setEmployeeId(employeeId);

        return memberRepository.save(member);
    }

    public AdminDepartmentMember updateMember(
            Long departmentId,
            Long memberId,
            AdminDepartmentMember updatedMember) {

        AdminDepartment department =
                departmentRepository.findById(departmentId)
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Department not found"
                                ));

        AdminDepartmentMember existingMember =
                memberRepository.findById(memberId)
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Member not found"
                                ));

        existingMember.setDepartment(department);
        existingMember.setFullName(
                updatedMember.getFullName()
        );
        existingMember.setEmail(
                updatedMember.getEmail()
        );

        /*
         * Do NOT update employee ID.
         *
         * Employee ID is permanent once generated.
         */
        
        existingMember.setDesignation(
                updatedMember.getDesignation()
        );

        return memberRepository.save(existingMember);
    }
}
